sudo: required
services:
  - docker

before_install:
  - docker build -t jeffvh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jeffvh/react-test npm test -- --coverage

after_success:
  - docker build -t jeffvh/k8s-multi-client ./client
  - docker build -t jeffvh/k8s-multi-nginx ./nginx
  - docker build -t jeffvh/k8s-multi-server ./server
  - docker build -t jeffvh/k8s-multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jeffvh/k8s-multi-client
  - docker push jeffvh/k8s-multi-nginx
  - docker push jeffvh/k8s-multi-server
  - docker push jeffvh/k8s-multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-multi-fibonacci
  env: DockerMultiFibonacci-env
  bucket_name: elasticbeanstalk-us-east-2-788408921554
  bucket_path: docker-multi-fibonacci
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY